databases:
  - name: boop_blog
    databaseName: boop_blog
    user: anthonyton

services:
  - type: web
    name: boop_blog
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
      fromDatabase:
        name: boop_blog
        property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
